version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ${TWS_DEPLOY_DIR}:/build
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - "loc-net"
      - "inner-net"
      
  peer:
    build:
      context: ./peerjs
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.0:80:8888
      
    networks:
      - "inner-net"


networks:
  inner-net:
  loc-net:
    name: verdaccio-local-net
    external: true